In [1]:
from actor_critic import actor_critic
import torch

In [2]:
worker = actor_critic(
    model_dim = 64,
    mlp_dim = 128,
    heads = 4,
    enc_layers = 2,
    dec_layers = 2,
    max_sequence = 100,
    n_players = 6,
    gamma = 0.99,
    n_actions = 14
    )

with torch.autograd.set_detect_anomaly(True):
    loss, adv, Qs, values, alps = worker.play_hand()
    print(loss)
    loss.backward(retain_graph=True)
    loss, adv, Qs, values, alps = worker.play_hand()
    print(loss)
    loss.backward()

tensor(2489957.7500, grad_fn=<AddBackward0>)
tensor(2231263.5000, grad_fn=<AddBackward0>)


/Users/ethanbanks/Library/Python/3.9/lib/python/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/ethanbanks/Library/Python/3.9/lib/python/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/Users/ethanbanks/Library/Python/3.9/lib/python/site-packages/traitlets/config/application.py", line 978, in launch_instance
    app.start()
  File "/Users/ethanbanks/Library/Python/3.9/lib/python/site-packages/ipykernel/kernelapp.py", line 712, in start
    self.io_loop.start()
  File "/

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
# nothing in self.values has grad enabled

In [3]:
adv.size(), Qs.size(), values.size(), alps.size()

(torch.Size([89, 6]),
 torch.Size([89, 6]),
 torch.Size([89, 6]),
 torch.Size([89, 6]))

In [4]:
alps.requires_grad

True

In [5]:
adv[0], Qs[0], values[0] #values does not have grad enabled for some reason

(tensor([ 9705.4717, 10550.7656,  9700.2686,  9835.2695, 10051.2852,  9799.9316],
        grad_fn=<SelectBackward0>),
 tensor([-294.5281,  550.7652, -299.7313, -164.7304,   51.2854, -200.0681],
        grad_fn=<SelectBackward0>),
 tensor([-10000., -10000., -10000., -10000., -10000., -10000.],
        grad_fn=<SelectBackward0>))

In [6]:
Qs

tensor([[-2.9453e+02,  5.5077e+02, -2.9973e+02, -1.6473e+02,  5.1285e+01,
         -2.0007e+02],
        [-2.9750e+02,  5.5633e+02, -3.0175e+02, -1.6639e+02,  5.1803e+01,
         -2.0209e+02],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,  5.2327e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -2.0619e+02],
        [-3.0661e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05,  5.7915e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -3.1730e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.7461e+02, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,  5.7703e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -2.1157e+02],
        [-3.1717e+02, -1.0000e

In [8]:
(-alps * adv).mean()

tensor(15.1399, grad_fn=<MeanBackward0>)

In [ ]:
alp