In [1]:
from actor_critic import actor_critic

In [2]:
worker = actor_critic(
    model_dim = 64,
    mlp_dim = 128,
    heads = 4,
    enc_layers = 2,
    dec_layers = 2,
    max_sequence = 100,
    n_players = 6,
    gamma = 0.99,
    n_actions = 14
    )


loss, adv, Qs, values = worker.play_hand()
print(loss)
loss.backward()

tensor(2426.5906, grad_fn=<AddBackward0>)


In [3]:
adv.size(), Qs.size(), values.size()

(torch.Size([51, 6]), torch.Size([51, 6]), torch.Size([51, 6]))

In [4]:
adv[0], Qs[0], values[0] #values does not have grad enabled for some reason

(tensor([  0.0000,   0.0000,   0.0000,   0.0000, -47.8655,   0.0000],
        grad_fn=<SelectBackward0>),
 tensor([-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -5.0021e+01,
         -1.0000e+05], grad_fn=<SelectBackward0>),
 tensor([-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -2.1551e+00,
         -1.0000e+05]))

In [5]:
Qs.masked_fill(values == -10000000, -10000000)

tensor([[-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -5.0021e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.1289e+02],
        [ 3.3506e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.1159e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.1486e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.1273e+02, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.1973e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e

In [6]:
adv

tensor([[   0.0000,    0.0000,    0.0000,    0.0000,  -47.8655,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000, -110.7676],
        [ 337.1689,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000, -109.5242,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000, -112.9057,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000, -110.8115,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000, -117.7889,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000, -116.6314,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,  -51.7349,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000, -121.9580],
        [ 37