In [1]:
from actor_critic import actor_critic
import torch

In [2]:
worker = actor_critic(
    model_dim = 64,
    mlp_dim = 128,
    heads = 4,
    enc_layers = 2,
    memory_layers=0,
    mem_length=20,
    dec_layers = 2,
    max_sequence = 100,
    n_players = 2,
    gamma = 1,
    n_actions = 14
    )

with torch.autograd.set_detect_anomaly(True):
    out = worker.play_hand()
    print(out[0])
    out[0].backward()

tensor([[1.0190e-04, 9.4033e-01],
        [1.0293e-04, 2.9700e+00],
        [1.0397e-04, 3.0000e+00]], grad_fn=<SliceBackward0>)
tensor([[-5.7830e+03, -5.7830e+03],
        [-5.7830e+03, -5.7830e+03],
        [ 1.2225e-04, -1.0000e+05]], grad_fn=<SliceBackward0>)
tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-2.5374e+00, -1.0000e+05]], grad_fn=<SliceBackward0>)
tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-1.8281e-05,  1.0000e+05]], grad_fn=<MaskedFillBackward0>)
tensor(1.6751e+09, grad_fn=<AddBackward0>)


In [ ]:
# nothing in self.values has grad enabled

In [3]:
with torch.autograd.set_detect_anomaly(True):
    out = worker.play_hand()
    print(out[0])
    out[0].backward()

tensor([[ 9.4071e-01,  4.0712e-04],
        [ 2.9704e+00,  4.1124e-04],
        [-1.0000e+05,  4.1539e-04]], grad_fn=<MaskedFillBackward0>)
tensor([[-5.7830e+03, -5.7830e+03],
        [-5.7830e+03, -5.7830e+03],
        [-1.0000e+05,  3.2461e-04]], grad_fn=<SliceBackward0>)
tensor([[ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [-1.0000e+05, -2.6237e+00]], grad_fn=<SliceBackward0>)
tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 9.0783e-05]], grad_fn=<MaskedFillBackward0>)
tensor(3.9698e-05, grad_fn=<AddBackward0>)


In [7]:
out

(tensor(199.2803, grad_fn=<AddBackward0>),
 tensor(115.8863, grad_fn=<MeanBackward0>),
 tensor(83.3940, grad_fn=<DivBackward0>),
 {'total': 1946482000,
  'env': 0,
  'model_inference': 1896153000,
  'loss': 10548000})

In [5]:
adv[0], Qs[0], values[0] #values does not have grad enabled for some reason

(tensor([ 9705.4717, 10550.7656,  9700.2686,  9835.2695, 10051.2852,  9799.9316],
        grad_fn=<SelectBackward0>),
 tensor([-294.5281,  550.7652, -299.7313, -164.7304,   51.2854, -200.0681],
        grad_fn=<SelectBackward0>),
 tensor([-10000., -10000., -10000., -10000., -10000., -10000.],
        grad_fn=<SelectBackward0>))

In [6]:
Qs

tensor([[-2.9453e+02,  5.5077e+02, -2.9973e+02, -1.6473e+02,  5.1285e+01,
         -2.0007e+02],
        [-2.9750e+02,  5.5633e+02, -3.0175e+02, -1.6639e+02,  5.1803e+01,
         -2.0209e+02],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,  5.2327e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -2.0619e+02],
        [-3.0661e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05,  5.7915e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -3.1730e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.7461e+02, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,  5.7703e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -2.1157e+02],
        [-3.1717e+02, -1.0000e

In [8]:
(-alps * adv).mean()

tensor(15.1399, grad_fn=<MeanBackward0>)

In [1]:
from decoder import decoderXL_layer

In [ ]:
block = decoderXL_layer(
    embed_dim=16,
    mlp_dim=20,
    attention_heads=4
    sequence_lenth=20,
    mem_length=10
)