In [1]:
from actor_critic import actor_critic
import torch

In [2]:
worker = actor_critic(
    model_dim = 64,
    mlp_dim = 128,
    heads = 4,
    enc_layers = 2,
    dec_layers = 2,
    max_sequence = 100,
    n_players = 6,
    gamma = 0.99,
    n_actions = 14
    )

with torch.autograd.set_detect_anomaly(True):
    loss, adv, Qs, values, alps = worker.play_hand()
    print(loss)
    loss.backward()

tensor([0.0217, 0.0344, 0.0217, 0.0000, 0.0217, 0.0582, 0.1367, 0.0605, 0.0217,
        0.0217, 0.0217, 0.0217, 0.0217, 0.5368], grad_fn=<SelectBackward0>)
True tensor(False)
tensor([0.0256, 0.0599, 0.0256, 0.0000, 0.0256, 0.0493, 0.1237, 0.0717, 0.0256,
        0.0256, 0.0256, 0.0256, 0.0256, 0.4906], grad_fn=<SelectBackward0>)
True tensor(False)
tensor([0.0193, 0.0357, 0.0193, 0.0000, 0.0193, 0.0612, 0.1212, 0.0509, 0.0193,
        0.0193, 0.0193, 0.0193, 0.0193, 0.5770], grad_fn=<SelectBackward0>)
True tensor(False)
tensor([0.0559, 0.1016, 0.0559, 0.0000, 0.0559, 0.0559, 0.1389, 0.1247, 0.0559,
        0.0559, 0.0559, 0.0559, 0.0559, 0.1317], grad_fn=<SelectBackward0>)
True tensor(False)
tensor([0.0445, 0.1905, 0.0445, 0.0000, 0.0686, 0.0766, 0.1052, 0.0996, 0.0719,
        0.0445, 0.0445, 0.0445, 0.0560, 0.1089], grad_fn=<SelectBackward0>)
True tensor(False)
tensor([0.0107, 0.8519, 0.0107, 0.0000, 0.0107, 0.0116, 0.0300, 0.0745, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.000

/Users/ethanbanks/Library/Python/3.9/lib/python/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in LogBackward0. No forward pass information available. Enable detect anomaly during forward pass for more information. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:97.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass


RuntimeError: Function 'LogBackward0' returned nan values in its 0th output.

In [ ]:
# nothing in self.values has grad enabled

In [3]:
adv.size(), Qs.size(), values.size(), alps.size()

(torch.Size([49, 6]),
 torch.Size([49, 6]),
 torch.Size([49, 6]),
 torch.Size([49, 6]))

In [4]:
alps.requires_grad

False

In [4]:
adv[0], Qs[0], values[0] #values does not have grad enabled for some reason

(tensor([  0.0000,   0.0000,   0.0000,   0.0000, -47.8655,   0.0000],
        grad_fn=<SelectBackward0>),
 tensor([-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -5.0021e+01,
         -1.0000e+05], grad_fn=<SelectBackward0>),
 tensor([-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -2.1551e+00,
         -1.0000e+05]))

In [5]:
Qs.masked_fill(values == -10000000, -10000000)

tensor([[-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -5.0021e+01,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.1289e+02],
        [ 3.3506e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.1159e+02, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.1486e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.1273e+02, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e+05, -1.1973e+02, -1.0000e+05, -1.0000e+05,
         -1.0000e+05],
        [-1.0000e+05, -1.0000e

In [6]:
adv

tensor([[   0.0000,    0.0000,    0.0000,    0.0000,  -47.8655,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000, -110.7676],
        [ 337.1689,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000, -109.5242,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000, -112.9057,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000, -110.8115,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000, -117.7889,    0.0000,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000, -116.6314,    0.0000,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,  -51.7349,    0.0000],
        [   0.0000,    0.0000,    0.0000,    0.0000,    0.0000, -121.9580],
        [ 37